name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Setup Java11"
        uses: actions/setup-java@v3
        with:
          java-version: 11
          cache: 'gradle'

      - name: "Build with Gradle"
        run: ./gradlew package --no-daemon

      - uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: true
          artifacts: "build/*.jar"
          token: ${{ secrets.TOKEN_FOR_RELEASE_ACTION }}
